using System.Diagnostics;
namespace SecureAgentLab.DocumentChecks.Fixtures;

internal static class CheckAssertions
{
    internal static void Assert(bool value, string message)
    {
        if (!value)
        {
            throw new InvalidOperationException(message);
        }
    }

    internal static void Equal<T>(T expected, T actual) => Assert(EqualityComparer<T>.Default.Equals(expected, actual), $"Expected {expected}, got {actual}");
    internal static void Throws<T>(Action run)
        where T : Exception
    {
        try
        {
            run();
        }
        catch (T)
        {
            return;
        }

        throw new InvalidOperationException("Expected " + typeof(T).Name);
    }

    internal static void LinkDirectory(string path, string target)
    {
        if (!OperatingSystem.IsWindows())
        {
            Directory.CreateSymbolicLink(path, target);
            return;
        }

        // Junction fixtures do not require Windows symbolic-link privilege. Paths are generated by this harness.
        string command = $"New-Item -ItemType Junction -Path '{path.Replace("'", "''")}' -Target '{target.Replace("'", "''")}' -ErrorAction Stop | Out-Null";
        using Process process = Process.Start(new ProcessStartInfo("powershell.exe") { CreateNoWindow = true, UseShellExecute = false, ArgumentList = { "-NoProfile", "-NonInteractive", "-Command", command } })!;
        process.WaitForExit();
        Equal(0, process.ExitCode);
    }
}
